apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: operator-gitops-demo-subscription
  namespace: openshift-marketplace
  labels:
    app: operator-gitops
  annotations:
    apps.open-cluster-management.io/github-path: operators
    apps.open-cluster-management.io/github-branch: master
spec:
  name: operator-gitops-demo-subscription
  channel: openshift/template-gitops-demo-channel
  placement:
    local: true
