apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: template-gitops-demo-subscription
  namespace: openshift
  labels:
    app: template-gitops
  annotations:
    apps.open-cluster-management.io/github-path: templates
    apps.open-cluster-management.io/github-branch: master
spec:
  name: template-gitops-demo-subscription
  channel: openshift/template-gitops-demo-channel
  placement:
    local: true
