apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: azure-service-operators
  namespace: openshift-marketplace
spec:
  displayName: Azure Service Operators
  publisher: StefanB

  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: sbergste